/*
 * NAME:
 *
 * PURPOSE:
 *
 * REQUIREMENTS:
 *
 * INPUT:
 *
 * OUTPUT:
 *
 * NOTES:
 *
 * BUGS:
 *
 * AUTHOR:
 * Øystein Godøy, met.no/FOU, 07.01.2005 
 *
 * MODIFIED BY:
 * Øystein Godøy, METNO/FOU, 2011-01-21: Changed fmesd.
 *
 * ID:
 * $Id$
 */

#include <math.h>
#include <fmutil_types.h>
#include <fmtime.h>
#include <fmcoord.h>
#include <fmangleconversion.h>
#include <fmsolar.h>

/*
 * FUNCTION:
 * fmesd
 * 
 * PURPOSE:
 * Estimates the variation of the distance between the Sun and the Earh
 * throughout the year using the equations specified in Paltridge and
 * Platt (1976) at page 57.
 *
 * NOTES:
 * doy should be in the range 1-365.
 * 
 * RETURN VALUES:
 * Returns the variation in AU (ratio of astronomic units). This is
 * multiplied with e.g. the solar constant to get the solar irradiance at
 * TOA.
 *
 * AUTHOR:
 * Øystein Godøy, met.no/FOU, 23.02.2004
 *
 * MODIFIED BY:
 * Øystein Godøy, METNO/FOU, 2011-01-21: Changed day of year range from
 * 0-364 to 1-365.
 */
double fmesd(int doy) {

    double d, theta0;

    theta0 = (2.*fmPI*doy-1)/365.0; /* in radians */

    d =(1.000110
	+0.034221*cos(theta0)
	+0.001280*sin(theta0)
	+0.000719*cos(2.*theta0)
	+0.000077*sin(2.*theta0));

    return(d);
}

/*
 * NAME:
 * declination
 *
 * PURPOSE:
 * To estimate the declination. This varies between -23.5 degrees on
 * December 22 and +23.5 on June 22.
 *
 * NOTES:
 * This function is base upon the equation given in Paltridge and Platt
 * (1976), page 63.  * One should check the behaviour of gmtime when
 * timezone is not set to UTC. The input doy variable is expected to be in
 * the range 0 to 364 (January 1 and December 31 respectively).
 *
 * BUGS:
 * NA
 *
 * REQUIREMENTS:
 * NA
 *
 * RETURN VALUES:
 * declination in radians.
 *
 * AUTHOR:
 * Øystein Godøy, met.no/FOU, 23.02.2004
 */
double fmdeclination(int doy){

    double decl, theta0;

    theta0 = (2.*fmPI*doy)/365.;

    decl= 0.006918
	-(0.399912*cos(theta0))
	+(0.070257*sin(theta0))
	-(0.006758*cos(2.*theta0))
	+(0.000907*sin(2.*theta0))
	-(0.002697*cos(3.*theta0))
	+(0.001480*sin(3.*theta0));

    return(decl);
}

/*
 * NAME:
 * equationoftime
 *
 * PURPOSE:
 * To estimate the difference between local time and true solar time.
 * Local time is the time transformed from some time zone dependency to
 * the local position, equation of time compensates for the irregular
 * behaviour of the Earth's orbit around the Sun.
 *
 * NOTES:
 * This function operates on time specified as seconds. The equation of
 * time depends on the day of the year. The current implementation is
 * given in at page 63 in Paltridge and Platt (1976). That equation is
 * specified in radians, this is converted to seconds within this code.
 * Day number of the year is expected to be generated by gmtime and to be
 * in the range 0 to 364.
 *
 * BUGS: 
 * NA
 *
 * RETURN VALUES: 
 * Seconds to compensate.
 *
 * AUTHOR: 
 * Øystein Godøy, met.no/FOU, 25.02.2004
 */
fmsec1970 fmequationoftime(int doy){

    fmsec1970 deltat;
    double theta0;

    /*
     * Convert from day number of year to radians.
     */
    theta0 = (2.*fmPI*doy)/365.;

    /*
     * Estimate equation of time in seconds. The original equation gives
     * it in radians which are converted to degrees by multiplication with
     * 180./PI, degrees are converted to seconds by multiplication of
     * 3600/15=240 (15 degrees is one hour).
     */
    deltat = (fmsec1970) floor(((0.000075+0.001868*cos(theta0)
	-0.032077*sin(theta0)
	-0.014615*cos(2.*theta0)
	-0.040849*sin(2.*theta0))
	*(180./fmPI)*240.)+0.5);
    
    return(deltat);
}

/*
 * FUNCTION:
 * sunz
 * 
 * PURPOSE:
 * Estimates the solar zenith angle for a given position in latitude
 * and longitude.
 *
 * INPUT:
 * 1. true solar time for the position specified as seconds since 1970.
 * 2. latitude in degrees
 * 
 * RETURN VALUES:
 * Solar zenith angle in degrees.
 * -999 is error
 *
 * AUTHOR:
 * Øystein Godøy, DNMI/FOU, xx.xx.xxxx
 * MODIFIED:
 * Øystein Godøy, met.no/FOU, 25.02.2004
 * Changed code to use standard functions available within this library.
 * Øystein Godøy, met.no/FOU, 04.11.2004
 * Øystein Godøy, METNO/FOU, 26.03.2010: Corrected bug due to erroneous
 * handling of true solar time and GMT time.
 */
double fmsolarzenith(fmsec1970 tst, fmgeopos gpos) {

    fmtime t;
    double decl, tsthour, hangle, et;
    double glat, glon;
    double coszensun, soz;
        
    /*
     * Set local variables.
     */
    glat = fmdeg2rad(gpos.lat);
    glon = fmdeg2rad(gpos.lon);

    /*
     * Get day number of year.
     */
    tofmtime(tst,&t);

    /*
     * Estimate the declination.
     */
    decl = fmdeclination(fmdayofyear(t));

    /*
     * Estimate the hour angle.
     */
    et = 0.170*sin(4*fmPI*(t.fm_yday-80.)/373.)
        -0.129*sin(2*fmPI*(t.fm_yday-8.)/355.);
    tsthour = (double) (t.fm_hour+((t.fm_min)/60.));
    hangle = fmhourangle(tsthour);
    
    /* 
     * Estimate the solar zenith angle.
     */
    coszensun = (cos(glat)*cos(hangle)*cos(decl))+(sin(glat)*sin(decl));
    soz = fmrad2deg((acos(coszensun)));

    return(soz);
}

/*
 * FUNCTION:
 * bidirref
 * 
 * PURPOSE:
 * To convert AVHRR albedo measurements to bi-directional reflectivities
 * according to (more or less) standard texts by correcting it for the
 * varying distance between the Earth and the Sun and transfer it from Sun
 * at zenith to the actual Solar zenith angle. It is assumed that data
 * from the MEOS system are converted from scaled integer to albedo values
 * in the range 0-100 before entering this routine. The routine will
 * return a value in the range 0-100 if input is in the range 0-100 or in
 * the range 0-1 if the input is in the range 0-1. It is assumed that
 * day of year is input in the range 1-365 and solar zenith angle in
 * degrees.
 * 
 * NOTES:
 * See HTML paper by Rao and Chen concerning recalibration of NOAA-14 and
 * CSIRO documentation concerning bi-directional reflectance.
 * 
 * BUGS:
 * NA
 *
 * AUTHOR:
 * Øystein Godøy, DNMI/FOU, 14/12/2001
 */
float fmbidirref(int jd, float soz, float alb) {

    float bidir, erv;

    erv = fmesd(jd-1);
    bidir = (erv*alb)/(cosf(soz*fmPI/180.));
    
    return(bidir);
}

/*
 * NAME:
 * toairrad
 *
 * PURPOSE:
 * To estimate the solar irradiance at TOA.
 *
 * NOTES:
 * This function operates on time specified as seconds since 1970, ie
 * standard UNIX time but specified as fmsec1970 and manipulated through
 * the fmtime code within libsatimg.
 *
 * BUGS:
 * NA
 *
 * REQUIREMENTS:
 * sunz
 * esd
 *
 * INPUT:
 * true solar time in seconds since 1970
 * geographical latitude in decimal degrees
 * solar constant to be used (W/m²)
 *
 * RETURN VALUES:
 * irradiance at TOA in W/m².
 *
 * AUTHOR:
 * Øystein Godøy, met.no/FOU, 23.02.2004
 *
 * MODIFIED:
 * Øystein Godøy, met.no/FOU, 23.12.2004
 * Changed sunz interface...
 */
double fmtoairrad(fmsec1970 tst, fmgeopos gpos, double s0){

    double toa;
    fmtime t;

    tofmtime(tst,&t);
    toa = s0*(fmesd(t.fm_yday))*fmdeg2rad((fmsolarzenith(tst,gpos)));

    return(toa);
}

